import pandas as pd
xls = pd.ExcelFile('yelp.xlsx')
print(type(xls))
df = xls.parse('yelp_data')#read the "yelp_data" sheet into a DataFrame
#df is a dataframe
print("type(df)")
print(type(df))
print("len(df)")
print(len(df))
print("df.shape")
print(df.shape)
print("df.count()")
print(df.count())
print("df.columns")
print(df.columns)
print("df.dtypes")
print(df.dtypes)
print("df.describe()")
print(df.describe())
print("df.head()")
print(df.head())
print("df.head(100)")
print(df.head(100))
print("df.drop_duplicates()")
print(df.drop_duplicates())
print("df[""name""]")
print(df["name"])
atts = ["name", "city_id", "state_id"]#stores the list of attributes in a list
print("df[atts].head(100)")
print(df[atts].head(100))
#
print("xls.parse('cities')")
print(xls.parse('cities'))
df_cities = xls.parse('cities')
print(df_cities.head())
pd.merge(left=df, right=df_cities, how='inner', left_on='city_id',right_on='id')
print(df.head())
df_states = xls.parse('states')
print(df_states.head())
df = pd.merge(left=df, right=df_states, how='inner' ,left_on='state_id', right_on='id')
print(df.shape)
print(df.head())

