import turtle
turtle.bgcolor("navyblue")

rec=turtle.Turtle()
rec.penup()
rec.pensize(5)
rec.goto(-220,-20)
rec.pendown()
rec.color('brown')
rec.begin_fill()
rec.left(90)
rec.forward(200)
rec.right(90)
rec.forward(550)
rec.right(90)
rec.forward(200)
rec.right(90)
rec.forward(550)
rec.end_fill()

letk=turtle.Turtle()
letk.pensize(5)
letk.pencolor("black")
letk.penup()
letk.goto(-200,0)
letk.pendown()
letk.left(90)
letk.forward(150)
letk.right(180)
letk.forward(75)
letk.left(120)
letk.forward(75)
letk.left(60)
letk.forward(37)
letk.backward(37)
letk.right(60)
letk.backward(75)
letk.right(60)
letk.forward(75)
letk.right(60)
letk.forward(37)

leti=turtle.Turtle()
leti.pensize(5)
leti.pencolor("black")
leti.penup()
leti.goto(-110,0)
leti.pendown()
leti.left(90)
leti.forward(150)

lett=turtle.Turtle()
lett.pensize(5)
lett.pencolor("black")
lett.penup()
lett.goto(-20,0)
lett.pendown()
lett.left(90)
lett.forward(150)
lett.left(90)
lett.forward(50)
lett.backward(100)
lett.penup()
lett.goto(-20,0)
lett.left(90)

letst=turtle.Turtle()
letst.pensize(5)
letst.pencolor("black")
letst.penup()
letst.goto(140,0)
letst.pendown()
letst.left(90)
letst.forward(150)
letst.left(90)
letst.forward(50)
letst.backward(100)
letst.penup()
letst.goto(140,0)
letst.left(90)

letu=turtle.Turtle()
letu.pensize(5)
letu.pencolor("black")
letu.penup()
letu.goto(220,0)
letu.pendown()
letu.left(90)
letu.forward(150)
letu.backward(150)
letu.right(90)
letu.forward(70)
letu.left(90)
letu.forward(150)


