import turtle
turtle.bgcolor("navyblue")


turtle.penup()
turtle.pensize(5)
turtle.goto(-170,75)
turtle.pendown()
turtle.shape("circle")
turtle.fillcolor("brown")
turtle.shapesize(13,5,2)

oval2=turtle.Turtle()
oval2.penup()
oval2.pensize(5)
oval2.goto(-110,75)
oval2.pendown()
oval2.shape("circle")
oval2.fillcolor("brown")
oval2.shapesize(13,2,2)      
  
oval3=turtle.Turtle()
oval3.penup()
oval3.pensize(5)
oval3.goto(0,75)
oval3.pendown()
oval3.shape("circle")
oval3.fillcolor("brown")
oval3.shapesize(13,10,2)      
  
oval4=turtle.Turtle()
oval4.penup()
oval4.pensize(5)
oval4.goto(150,75)
oval4.pendown()
oval4.shape("circle")
oval4.fillcolor("brown")
oval4.shapesize(13,10,2)

  
oval5=turtle.Turtle()
oval5.penup()
oval5.pensize(5)
oval5.goto(260,75)
oval5.pendown()
oval5.shape("circle")
oval5.fillcolor("brown")
oval5.shapesize(13,7,2)



letk=turtle.Turtle()
letk.pensize(5)
letk.pencolor("black")
letk.penup()
letk.goto(-200,0)
letk.pendown()
letk.left(90)
letk.forward(150)
letk.right(180)
letk.forward(75)
letk.left(120)
letk.forward(75)
letk.left(60)
letk.forward(37)
letk.backward(37)
letk.right(60)
letk.backward(75)
letk.right(60)
letk.forward(75)
letk.right(60)
letk.forward(37)

leti=turtle.Turtle()
leti.pensize(5)
leti.pencolor("black")
leti.penup()
leti.goto(-110,0)
leti.pendown()
leti.left(90)
leti.forward(150)

lett=turtle.Turtle()
lett.pensize(5)
lett.pencolor("black")
lett.penup()
lett.goto(-20,0)
lett.pendown()
lett.left(90)
lett.forward(150)
lett.left(90)
lett.forward(50)
lett.backward(100)
lett.penup()
lett.goto(-20,0)
lett.left(90)

letst=turtle.Turtle()
letst.pensize(5)
letst.pencolor("black")
letst.penup()
letst.goto(140,0)
letst.pendown()
letst.left(90)
letst.forward(150)
letst.left(90)
letst.forward(50)
letst.backward(100)
letst.penup()
letst.goto(140,0)
letst.left(90)

letu=turtle.Turtle()
letu.pensize(5)
letu.pencolor("black")
letu.penup()
letu.goto(220,0)
letu.pendown()
letu.left(90)
letu.forward(150)
letu.backward(150)
letu.right(90)
letu.forward(70)
letu.left(90)
letu.forward(150)

dot1=turtle.Turtle()
dot1.penup()
dot1.goto(240,130)
dot1.pendown()
dot1.dot(20)
dot1.penup()
dot1.goto(270,130)
dot1.pendown()
dot1.dot(20)

turtle.bgcolor("green")



